### ISSUE TITLE
Links for KubeWeekly #155

### ISSUE THREAD

**Issue by kbarnard10** [cncf/ambassadors#39]
Links due by 11am PT on Wednesday November 7th.

**Comment by leecalcote** [comment]
@kbarnard10, here's an editor's pick - a short book that didn't make the cut in time for the 154 weekly - -

[_The Enterprise Path to Service Mesh Architectures_](https://gingergeek.com/2018/08/now-available-the-enterprise-path-to-service-mesh-architectures/)
_Lee Calcote, Layer5_

If you scratch your head at what a service mesh is and how they provide a necessary layer of services tooling distinct from API gateways and container orchestrators, download this free short book authored by one of our own Cloud Native Ambassadors - Lee Calcote. Be sure to visit [Layer5.io](https://layer5.io/landscape) for detailed survey of the service mesh landscape.

**Comment by chris-short** [comment]
Here is everything I think is worth sharing is this week. I think it'd be best if @kbarnard10 organizes them as categorizing things is hard enough but, wait until there's a conflict (editorial vs. technical, etc.).

* [The Journey to Kubernetes](https://www.weave.works/blog/the-journey-to-kubernetes) — "Have you wondered why Kubernetes is so popular? Discover why Kubernetes is the clear market leader in the container orchestration space in our latest addition to the Kubernetes library."

* [KRS: A new tool for gathering Kubernetes resource statistics](https://opensource.com/article/18/11/kubernetes-resource-statistics) — Zero-configuraton tool simplifies gathering information, such as how many pods are running in a certain namespace.

* [Using Kubernetes ConfigMap Resources for Dynamic Apps](https://medium.com/capital-one-tech/using-kubernetes-configmap-resources-for-dynamic-apps-9e23ef589121) — "we decided to build a Golang application that would map part of its filesystem to a Kubernetes configmap resource."

* [Exploring container security: running and connecting to HashiCorp Vault on Kubernetes](https://cloud.google.com/blog/products/identity-security/exploring-container-security-running-and-connecting-to-hashicorp-vault-on-kubernetes) — Seth Vargo explains how Hashicorp Vault and Kubernetes work together.

* [The Beginner’s Guide to the CNCF Landscape](https://www.cloudops.com/2018/10/the-beginners-guide-to-the-cncf-landscape/) — The CNCF landscape continues to grow but, if you're just starting down the path, where do you begin? Ayrat Khayretdinov of CloudOps provides a wonderful guide.

* [turkenh/KubeContext](https://github.com/turkenh/kubecontext) — Menu Bar App for Managing Kubernetes Contexts on Mac

* [Helm from basics to advanced](https://banzaicloud.com/blog/creating-helm-charts/) — Get productive with Helm

* [Who Is Running My Kubernetes Pod? The Past, Present, and Future of Container Runtimes](https://www.infoq.com/articles/container-runtimes-kubernetes) — "Between the OCI and the CRI, interoperability and choice is becoming a reality in the container runtime and orchestration ecosystem"

* [HUMBLE BOOK BUNDLE: DEVOPS BY O'REILLY](https://www.humblebundle.com/books/dev-ops-oreilly) — Kubernetes: Up and Running, Cloud Native Infrastructure, and Prometheus: Up and Running in one Humble Bundle? Shut up and take my money.

* [You might not need Kubernetes](https://blog.jessfraz.com/post/you-might-not-need-k8s/): Just because Kubernetes is solving problems for a lot of folks right now doesn't mean the people using Kubernetes to solve those problems are shills for the technology.

* [Embracing failures and cutting infrastructure costs: Spot instances in Kubernetes](https://learnk8s.io/blog/kubernetes-spot-instances)

* [Kubernetes' scheduling magic revealed](https://www.oreilly.com/ideas/kubernetes-scheduling-magic-revealed) — Understanding how the Kubernetes scheduler makes scheduling decisions is critical to ensure consistent performance and optimal resource utilization.

* [Istio: The Enterprise Upgrade Path to Microservices](https://blog.aquasec.com/istio-kubernetes-service-mesh) — Istio brings a lot to the table for folks running or wanting to run more microservices.

**Comment by mrbobbytables** [comment]
Editorial:
* [[presentation] Scaling and Operating Kafka in Kubernetes](https://speakerdeck.com/brouberol/scaling-and-operating-kafka-in-kubernetes) ([video](https://www.youtube.com/watch?v=7eEOzguzOg0))  - A presentation from DataDog on how they manage a large scale Kafka deployment on top of Kubernetes.
