### ISSUE TITLE
KubeWeekly #166 - Week March 27th

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/ambassadors#52]
Please respond to this issue with links for the next edition of KubeWeekly. Links are due by 11am PT every Wednesday. @kbarnard10 will combine the links into the final email and send out. 

**Featured Content**
_Editor's picks of the highlights from the past week._
[ARTICLE TITLE](LINK)

**Technical** 
_Tutorials, tools, and more that take you on a deep dive into the code._
[ARTICLE TITLE](LINK)

_Tooling:_
[ARTICLE TITLE](LINK) - one sentence description

**The Editorial** 
_Articles, announcements, and more that give you a high-level overview of challenges and features._
[ARTICLE TITLE](LINK)

**GUIDELINES**
- Articles must be published within the last ~1 week. 
- No gated content, unless in the webinar section. 
- Blog posts and videos are the preferred medium.

**Comment by mrbobbytables** [comment]
**Editorial:**
- [Managing Kubernetes RBAC Groups](https://medium.com/cruise/open-sourcing-rbacsync-48758df685b0) - (Could also be tool, open sourced [rbacsync](https://github.com/cruise-automation/rbacsync))
- [Kubernetes-based Microservice Observability with Istio Service Mesh: Part 2](https://itnext.io/kubernetes-based-microservice-observability-with-istio-service-mesh-part-2-f25c4b474a65)
- [How to use Knative to deploy a Serverless Application on Kubernetes](https://itnext.io/how-to-use-knative-on-kubernetes-to-deploy-a-serverless-application-582d62fa2a9f)
- [Litmus: Journey of a storage e2e and chaos framework for Kubernetes](https://blog.openebs.io/litmus-journey-of-a-storage-e2e-and-chaos-framework-for-kubernetes-dc09a3904a24)

**Tooling:**
- [kubectl-who-can](https://github.com/aquasecurity/kubectl-who-can) - Show who has permissions to `<verb> <resources>` in kubernetes.

**Comment by chris-short** [comment]
[Tuning Jaeger’s performance](https://medium.com/jaegertracing/tuning-jaegers-performance-7a60864cf3b1) — This post will help you fine tune your individual Jaeger components to better match the needs of your particular deployment scenario.

[The evolution of serverless and FaaS: Knative brings change](https://developers.redhat.com/blog/2019/03/26/serverless-faas-knative/) — Knative disrupted all that by making any service available as a function, in that Knative allows a service to scale to zero after a configured period of time.

[Going Cloud Native: 6 essential things you need to know](https://www.weave.works/blog/going-cloud-native-6-essential-things-you-need-to-know) — This article discusses the key takeaways to know about the term cloud native. It also describes how you can take advantage of cloud native capabilities to speed up your development team’s productivity and increase your company’s innovation output.

[How to build your own CDN with Kubernetes](https://blog.insightdatascience.com/how-to-build-your-own-cdn-with-kubernetes-5cab00d5c258) — In this blog post, I discuss the design and implementation of kubeCDN, a tool designed to simplify geo-replication of Kubernetes clusters in order to deploy services with high availability on a global scale.

[Bringing Kubernetes to the bare-metal edge](https://opensource.com/article/19/3/bringing-kubernetes-bare-metal-edge) — New Kubespray features enable Kubernetes clusters to be deployed across next-generation edge locations.

[Kubernetes Learning Resources](https://docs.google.com/spreadsheets/d/10NltoF_6y3mBwUzQ4bcQLQfCE1BWSgUDcJXy-Qp2JEU/htmlview) — A Google Sheet full of useful resources

[A Self-Hosted Global Load Balancer for OpenShift](https://blog.openshift.com/a-self-hosted-global-load-balancer-for-openshift/) — In this post, we will implement that architecture, building upon the concepts from the last four posts. We will also see how it is possible to host the global load balancer in the federated clusters themselves, achieving a self-hosted global load balancer.

[PostgreSQL anywhere — via Kubernetes with some help from OpenEBS and credativ engineering](https://blog.openebs.io/postgresql-anywhere-via-kubernetes-with-some-help-from-openebs-and-credativ-engineering-c1c8b4bb1684) — In this blog, we’d like to briefly cover how using cloud-native or “container attached” storage can help in the deployment and ongoing operations of PostgreSQL on Kubernetes.

**Comment by danieloh30** [comment]
Technical
[Getting started with Jaeger to build an Istio service mesh](https://opensource.com/article/19/3/getting-started-jaeger) -Improve monitoring and tracing of cloud-native apps on a distributed networking system with Kubernetes and Istio.

**Comment by mrbobbytables** [comment]
**Featured Content:**
- [Minikube hit 1.0](https://github.com/kubernetes/minikube/releases/tag/v1.0.0)

**Comment by chris-short** [comment]
I think we can close this @caniszczyk
